const STORAGE_KEYS = {
  state: "assistant_state",
  prefs: "assistant_prefs",
  logs: "assistant_logs"
};

const SCENE_LABELS = {
  size: "尺码咨询",
  shipping: "发货时效",
  logistics: "物流查询",
  return_exchange: "退换售后",
  negative_review: "差评安抚",
  general: "通用咨询"
};

const SOURCE_LABELS = {
  rule: "规则引擎",
  model: "模型增强"
};

const TONES = ["professional", "friendly", "firm"];

const elements = {
  latestMessage: document.getElementById("latestMessage"),
  sceneLabel: document.getElementById("sceneLabel"),
  toneButtons: Array.from(document.querySelectorAll(".tone-btn")),
  autoGenerateEnabled: document.getElementById("autoGenerateEnabled"),
  autoCopyEnabled: document.getElementById("autoCopyEnabled"),
  generateAndCopyBtn: document.getElementById("generateAndCopyBtn"),
  generateBtn: document.getElementById("generateBtn"),
  copyBtn: document.getElementById("copyBtn"),
  openSettingsBtn: document.getElementById("openSettingsBtn"),
  sourceTag: document.getElementById("sourceTag"),
  statusLine: document.getElementById("statusLine"),
  replyOutput: document.getElementById("replyOutput"),
  violationHint: document.getElementById("violationHint"),
  recentLogs: document.getElementById("recentLogs"),
  manualMessageInput: document.getElementById("manualMessageInput"),
  applyManualMessageBtn: document.getElementById("applyManualMessageBtn"),
  applyAndGenerateManualBtn: document.getElementById("applyAndGenerateManualBtn"),
  chipButtons: Array.from(document.querySelectorAll(".chip-btn"))
};

let latestReplyText = "";
let selectedTone = "professional";
let typingTimer = 0;
let isGenerating = false;
let lastAutoGeneratedMessage = "";
let currentStateCache = null;
let currentPrefsCache = null;

function sendMessage(payload) {
  return new Promise((resolve) => {
    chrome.runtime.sendMessage(payload, (response) => {
      if (chrome.runtime.lastError) {
        resolve({ ok: false, error: chrome.runtime.lastError.message });
        return;
      }
      resolve(response || { ok: false, error: "NO_RESPONSE" });
    });
  });
}

function escapeHtml(value) {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function setStatus(text, level = "") {
  elements.statusLine.textContent = text;
  elements.statusLine.className = `status-line${level ? ` ${level}` : ""}`;
}

function renderScene(scene) {
  const label = SCENE_LABELS[scene] || "未识别";
  elements.sceneLabel.textContent = `场景：${label}`;
}

function renderSource(source) {
  const label = SOURCE_LABELS[source] || "规则引擎";
  elements.sourceTag.textContent = label;
}

function renderLatestMessage(message) {
  const text = String(message || "").trim();
  if (!text) {
    elements.latestMessage.textContent = "暂无用户消息，请在淘宝/闲鱼/飞猪客服页等待新消息。";
    return;
  }
  elements.latestMessage.textContent = text;
}

function renderRecentLogs(logs) {
  const list = (logs || []).slice(-6).reverse();
  if (list.length === 0) {
    elements.recentLogs.innerHTML = "<li>暂无操作记录</li>";
    return;
  }
  elements.recentLogs.innerHTML = list
    .map((item) => {
      const level = item?.level || "info";
      return `<li class="${level}">${escapeHtml(item?.text || "")}</li>`;
    })
    .join("");
}

function renderViolationHint(violations) {
  if (!violations || violations.length === 0) {
    elements.violationHint.className = "violation-hint ok";
    elements.violationHint.textContent = "未检测到违禁词。";
    return;
  }
  const words = [...new Set(violations.map((item) => item.word))];
  elements.violationHint.className = "violation-hint warn";
  elements.violationHint.textContent = `检测到违禁词：${words.join("、")}，请人工确认后再发送。`;
}

function highlightViolations(text, violations) {
  let output = escapeHtml(text);
  const words = [...new Set((violations || []).map((item) => item.word).filter(Boolean))];
  for (const word of words) {
    const reg = new RegExp(escapeRegex(escapeHtml(word)), "g");
    output = output.replace(reg, `<span class="violation-mark">${escapeHtml(word)}</span>`);
  }
  return output;
}

function setToneButtonsActive(tone) {
  for (const button of elements.toneButtons) {
    button.classList.toggle("is-active", button.dataset.tone === tone);
  }
}

function stopTyping() {
  if (typingTimer) {
    window.clearTimeout(typingTimer);
    typingTimer = 0;
  }
}

function flashCopyButton(text) {
  elements.copyBtn.textContent = text;
  window.setTimeout(() => {
    elements.copyBtn.textContent = "复制当前";
  }, 900);
}

function hasLatestMessage() {
  return Boolean(String(currentStateCache?.latestUserMessage || "").trim());
}

function syncGenerateButtons() {
  const disabled = isGenerating || !hasLatestMessage();
  elements.generateBtn.disabled = disabled;
  elements.generateAndCopyBtn.disabled = disabled;
}

function syncCopyButtonDisabled() {
  elements.copyBtn.disabled = isGenerating || !latestReplyText;
}

function typewriterRender(text, done) {
  stopTyping();
  elements.replyOutput.textContent = "";
  let index = 0;
  const total = text.length;
  const step = () => {
    const nextIndex = Math.min(total, index + (total > 200 ? 2 : 1));
    elements.replyOutput.textContent = text.slice(0, nextIndex);
    index = nextIndex;
    if (index < total) {
      typingTimer = window.setTimeout(step, 12);
      return;
    }
    typingTimer = 0;
    done();
  };
  step();
}

function setGeneratingState(generating) {
  isGenerating = generating;
  syncGenerateButtons();
  elements.applyManualMessageBtn.disabled = generating;
  elements.applyAndGenerateManualBtn.disabled = generating;
  elements.generateBtn.textContent = generating ? "生成中..." : "仅生成";
  elements.generateAndCopyBtn.textContent = generating ? "生成中..." : "生成并复制";
  syncCopyButtonDisabled();
}

async function applyPrefsPatch(patch) {
  const result = await sendMessage({
    type: "ASSISTANT_UPDATE_PREFS",
    payload: patch
  });
  if (result?.ok) {
    currentPrefsCache = {
      ...(currentPrefsCache || {}),
      ...patch
    };
  }
}

async function copyLatestReply(options = {}) {
  const { silentStatus = false, fromAuto = false } = options;
  if (!latestReplyText) {
    return false;
  }
  try {
    await navigator.clipboard.writeText(latestReplyText);
    await sendMessage({
      type: "ASSISTANT_APPEND_LOG",
      payload: { text: fromAuto ? "已自动复制建议话术" : "已执行一键复制", level: "info" }
    });
    if (!silentStatus) {
      setStatus("已复制到剪贴板，直接粘贴即可。", "ok");
    }
    flashCopyButton(fromAuto ? "已自动复制" : "已复制");
    return true;
  } catch (_error) {
    await sendMessage({
      type: "ASSISTANT_APPEND_LOG",
      payload: { text: "一键复制失败，请手动复制", level: "warn" }
    });
    if (!silentStatus) {
      setStatus("复制失败，请手动复制。", "warn");
    }
    flashCopyButton("复制失败");
    return false;
  }
}

async function generateReply(reasonText, options = {}) {
  const { copyAfterGenerate = false, respectAutoCopy = true } = options;
  if (isGenerating) {
    return;
  }
  if (!currentStateCache?.latestUserMessage) {
    setStatus("暂无可生成的买家消息。", "warn");
    return;
  }

  setGeneratingState(true);
  setStatus(reasonText || "正在生成建议话术...");

  const result = await sendMessage({
    type: "ASSISTANT_GENERATE_REPLY",
    payload: { tone: selectedTone }
  });

  setGeneratingState(false);

  if (!result?.ok) {
    latestReplyText = "";
    syncCopyButtonDisabled();
    elements.replyOutput.textContent =
      result?.error === "NO_MESSAGE"
        ? "暂无可生成的用户消息，请在淘宝/闲鱼/飞猪聊天页等待新消息。"
        : `生成失败：${result?.message || result?.error || "未知错误"}`;
    renderViolationHint([]);
    setStatus("生成失败，请重试。", "warn");
    return;
  }

  const data = result.data || {};
  latestReplyText = data.reply || "";
  syncCopyButtonDisabled();
  renderScene(data.scene || "general");
  renderSource(data.source || "rule");
  renderViolationHint(data.violations || []);

  typewriterRender(latestReplyText, () => {
    elements.replyOutput.innerHTML = highlightViolations(latestReplyText, data.violations || []);
  });

  const shouldAutoCopy = Boolean(copyAfterGenerate || (respectAutoCopy && currentPrefsCache?.autoCopyEnabled));
  if (shouldAutoCopy && latestReplyText) {
    const copied = await copyLatestReply({ silentStatus: true, fromAuto: true });
    if (copied) {
      setStatus(`已生成${data.source === "model" ? "模型增强" : "规则引擎"}建议并复制。`, "ok");
      return;
    }
    setStatus("话术已生成，但复制失败，请点击“复制当前”。", "warn");
    return;
  }

  setStatus(`已生成${data.source === "model" ? "模型增强" : "规则引擎"}建议，可直接复制。`, "ok");
}

async function onGenerateClick() {
  await generateReply("正在生成建议话术...");
}

async function onGenerateAndCopyClick() {
  await generateReply("正在生成并准备复制...", { copyAfterGenerate: true });
}

async function onCopyClick() {
  await copyLatestReply();
}

async function onToneClick(button) {
  const tone = button.dataset.tone;
  if (!TONES.includes(tone)) {
    return;
  }
  selectedTone = tone;
  setToneButtonsActive(tone);
  await applyPrefsPatch({ tone });
  setStatus("语气已切换，点击生成即可刷新建议。");
}

async function onAutoGenerateChange() {
  const enabled = elements.autoGenerateEnabled.checked;
  await applyPrefsPatch({ autoGenerateEnabled: enabled });
  setStatus(enabled ? "已开启自动生成。" : "已关闭自动生成。");
}

async function onAutoCopyChange() {
  const enabled = elements.autoCopyEnabled.checked;
  await applyPrefsPatch({ autoCopyEnabled: enabled });
  setStatus(enabled ? "已开启自动复制。" : "已关闭自动复制。");
}

async function onOpenSettingsClick() {
  await chrome.runtime.openOptionsPage();
}

function getManualMessageText() {
  return String(elements.manualMessageInput.value || "")
    .replace(/\s+/g, " ")
    .trim();
}

function applyManualMessageToView(text, scene = "general") {
  const oldState = currentStateCache || {};
  const nextState = {
    ...oldState,
    latestUserMessage: text,
    latestScene: scene
  };
  hydrateStateView(nextState);
}

async function injectManualMessage(options = {}) {
  const { withGenerate = false } = options;
  const text = getManualMessageText();
  if (!text) {
    setStatus("请先输入测试消息。", "warn");
    return;
  }

  const result = await sendMessage({
    type: "ASSISTANT_NEW_USER_MESSAGE",
    payload: { text }
  });

  if (!result?.ok) {
    setStatus("测试消息写入失败，请重试。", "warn");
    return;
  }

  applyManualMessageToView(text, result.latestScene || "general");
  setStatus(withGenerate ? "测试消息已写入，正在生成建议..." : "测试消息已写入，可直接点击生成。", "ok");

  if (withGenerate) {
    await generateReply("已写入测试消息，正在生成建议...");
  }
}

function onChipClick(button) {
  const example = String(button.dataset.example || "").trim();
  if (!example) {
    return;
  }
  elements.manualMessageInput.value = example;
  setStatus("已填充示例消息，可点击“写入并生成”。");
}

function hydrateStateView(state) {
  currentStateCache = state || null;
  renderLatestMessage(state?.latestUserMessage || "");
  renderScene(state?.latestScene || "general");
  renderSource(state?.lastSource || "rule");

  if (state?.lastGeneratedReply) {
    latestReplyText = state.lastGeneratedReply;
    elements.replyOutput.innerHTML = highlightViolations(state.lastGeneratedReply, state.lastViolations || []);
    renderViolationHint(state.lastViolations || []);
  } else {
    latestReplyText = "";
    renderViolationHint([]);
  }
  syncGenerateButtons();
  syncCopyButtonDisabled();
}

function hydratePrefsView(prefs) {
  currentPrefsCache = prefs || null;
  selectedTone = TONES.includes(prefs?.tone) ? prefs.tone : "professional";
  setToneButtonsActive(selectedTone);
  elements.autoGenerateEnabled.checked = Boolean(prefs?.autoGenerateEnabled ?? true);
  elements.autoCopyEnabled.checked = Boolean(prefs?.autoCopyEnabled ?? false);
}

async function maybeAutoGenerate(previousState, nextState) {
  const autoGenerateEnabled = Boolean(currentPrefsCache?.autoGenerateEnabled ?? true);
  if (!autoGenerateEnabled || isGenerating) {
    return;
  }
  const prevMessage = String(previousState?.latestUserMessage || "").trim();
  const nextMessage = String(nextState?.latestUserMessage || "").trim();
  if (!nextMessage || prevMessage === nextMessage) {
    return;
  }
  if (lastAutoGeneratedMessage === nextMessage) {
    return;
  }
  lastAutoGeneratedMessage = nextMessage;
  await generateReply("检测到新消息，已自动生成建议...");
}

function shouldIgnoreHotkey(event) {
  if (event.isComposing) {
    return true;
  }
  const target = event.target;
  if (!target) {
    return false;
  }
  if (target instanceof HTMLElement && target.isContentEditable) {
    return true;
  }
  const tag = (target.tagName || "").toUpperCase();
  return tag === "INPUT" || tag === "TEXTAREA" || tag === "SELECT";
}

function bindEvents() {
  elements.generateBtn.addEventListener("click", onGenerateClick);
  elements.generateAndCopyBtn.addEventListener("click", onGenerateAndCopyClick);
  elements.copyBtn.addEventListener("click", onCopyClick);
  elements.openSettingsBtn.addEventListener("click", onOpenSettingsClick);
  elements.applyManualMessageBtn.addEventListener("click", async () => {
    await injectManualMessage({ withGenerate: false });
  });
  elements.applyAndGenerateManualBtn.addEventListener("click", async () => {
    await injectManualMessage({ withGenerate: true });
  });
  elements.autoGenerateEnabled.addEventListener("change", onAutoGenerateChange);
  elements.autoCopyEnabled.addEventListener("change", onAutoCopyChange);
  for (const button of elements.chipButtons) {
    button.addEventListener("click", () => {
      onChipClick(button);
    });
  }

  window.addEventListener("keydown", (event) => {
    if (shouldIgnoreHotkey(event) || isGenerating) {
      return;
    }
    if (event.key !== "Enter") {
      return;
    }
    event.preventDefault();
    if (event.ctrlKey || event.metaKey) {
      void onGenerateAndCopyClick();
      return;
    }
    void onGenerateClick();
  });

  for (const button of elements.toneButtons) {
    button.addEventListener("click", async () => {
      await onToneClick(button);
    });
  }
}

async function loadInitialData() {
  const result = await sendMessage({
    type: "ASSISTANT_GET_STATE"
  });
  if (!result?.ok) {
    elements.replyOutput.textContent = "初始化失败，请刷新页面后重试。";
    setStatus("初始化失败。", "warn");
    return;
  }

  const { state, prefs, logs } = result.data;
  hydratePrefsView(prefs || {});
  hydrateStateView(state || {});
  renderRecentLogs(logs || []);

  const hasMessage = Boolean(String(state?.latestUserMessage || "").trim());
  const hasReply = Boolean(String(state?.lastGeneratedReply || "").trim());
  if (Boolean(prefs?.autoGenerateEnabled ?? true) && hasMessage && !hasReply) {
    lastAutoGeneratedMessage = String(state?.latestUserMessage || "").trim();
    await generateReply("已根据最新消息自动生成建议...", { respectAutoCopy: false });
    return;
  }
  setStatus("准备就绪");
}

function watchStorageChanges() {
  chrome.storage.onChanged.addListener((changes, areaName) => {
    if (areaName !== "local") {
      return;
    }
    if (changes[STORAGE_KEYS.prefs]) {
      hydratePrefsView(changes[STORAGE_KEYS.prefs].newValue || {});
    }
    if (changes[STORAGE_KEYS.state]) {
      const previousState = changes[STORAGE_KEYS.state].oldValue || {};
      const nextState = changes[STORAGE_KEYS.state].newValue || {};
      hydrateStateView(nextState);
      void maybeAutoGenerate(previousState, nextState);
    }
    if (changes[STORAGE_KEYS.logs]) {
      renderRecentLogs(changes[STORAGE_KEYS.logs].newValue || []);
    }
  });
}

async function bootstrap() {
  bindEvents();
  watchStorageChanges();
  await loadInitialData();
}

bootstrap();

